project_id = "lhijsbkijbdctsdlcxgg"

[functions.submit-quote-request]
verify_jwt = false

[functions.send-booking-notification]
verify_jwt = false

[functions.send-client-confirmation]
verify_jwt = false